apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-frontend
  template:
    metadata:
      labels:
        app: ai-frontend
    spec:
      containers:
      - name: ai-frontend
        image: localhost:5000/ai-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend
spec:
  selector:
    app: ai-frontend
  ports:
  - port: 94
    targetPort: 80
  type: ClusterIP
