apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  replicas: 4
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
      - name: joomla
        image: joomla:latest
        ports:
        - containerPort: 80
        env:
        - name: JOOMLA_DB_HOST
          value: joomla-mysql
        - name: JOOMLA_DB_USER
          value: joomla
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: JOOMLA_DB_NAME
          value: joomla
        volumeMounts:
        - name: joomla-settings
          mountPath: /var/www/html/configuration.php
          subPath: configuration.php
      volumes:
      - name: joomla-settings
        configMap:
          name: joomla-config
---
apiVersion: v1
kind: Service
metadata:
  name: joomla
spec:
  selector:
    app: joomla
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: joomla-config
data:
  configuration.php: |
    <?php
    class JConfig {
        /* Modified Joomla config with iframe settings */
        public $offline = '0';
        public $offline_message = 'This site is down for maintenance.<br>Please check back again soon.';
        public $display_offline_message = '1';
        public $offline_image = '';
        public $sitename = 'Web Store Demo';
        public $editor = 'tinymce';
        public $captcha = '0';
        public $list_limit = '20';
        public $access = '1';
        public $debug = '0';
        public $debug_lang = '0';
        public $debug_lang_const = '1';
        public $dbtype = 'mysqli';
        public $host = 'joomla-mysql';
        public $user = 'joomla';
        public $password = 'password';
        public $db = 'joomla';
        public $dbprefix = 'jos_';
        public $live_site = '';
        public $secret = 'fY2xsOGpXazZUdXI4d2RrNTNLUlFWV1RzMUtOYTlPV3c=';
        public $gzip = '0';
        public $error_reporting = 'default';
        public $helpurl = 'https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}';
        public $ftp_host = '';
        public $ftp_port = '21';
        public $ftp_user = '';
        public $ftp_pass = '';
        public $ftp_root = '';
        public $ftp_enable = '0';
        public $tmp_path = '/tmp';
        public $log_path = '/administrator/logs';
        public $mailer = 'mail';
        public $mailfrom = 'admin@example.com';
        public $fromname = 'Web Store Demo';
        public $sendmail = '/usr/sbin/sendmail';
        public $smtpauth = '0';
        public $smtpuser = '';
        public $smtppass = '';
        public $smtphost = 'localhost';
        public $smtpsecure = 'none';
        public $smtpport = '25';
        public $caching = '0';
        public $cache_handler = 'file';
        public $cachetime = '15';
        public $cache_platformprefix = '0';
        public $MetaDesc = 'Web Store Demo with Chat and AI';
        public $MetaKeys = '';
        public $MetaTitle = '1';
        public $MetaAuthor = '1';
        public $MetaVersion = '0';
        public $robots = '';
        public $sef = '1';
        public $sef_rewrite = '0';
        public $sef_suffix = '0';
        public $unicodeslugs = '0';
        public $feed_limit = '10';
        public $feed_email = 'none';
        public $log_path_admin = '';
        public $frontediting = '1';
        public $asset_id = '1';
        public $session_handler = 'database';
        public $shared_session = '0';
        public $session_metadata = '1';
        public $custom_fields_enable = '1';
        public $proxy_enable = '0';
        public $proxy_host = '';
        public $proxy_port = '';
        public $proxy_user = '';
        public $proxy_pass = '';
        public $memcached_persist = '1';
        public $memcached_compress = '0';
        public $memcached_server_host = 'localhost';
        public $memcached_server_port = '11211';
        public $redis_persist = '1';
        public $redis_server_host = 'localhost';
        public $redis_server_port = '6379';
        public $redis_server_auth = '';
        public $redis_server_db = '0';
        public $lifetime = '15';
        public $session_memcached_server_host = 'localhost';
        public $session_memcached_server_port = '11211';
        public $session_redis_persist = '1';
        public $session_redis_server_host = 'localhost';
        public $session_redis_server_port = '6379';
        public $session_redis_server_db = '0';
        public $massmailoff = '0';
        public $replyto = '';
        public $replytoname = '';
        public $offset = 'UTC';
        public $mailonline = '1';
        public $session_memcache_server_host = 'localhost';
        public $session_memcache_server_port = '11211';
    }
