apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: cGFzc3dvcmQ=  # "password" in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
type: Opaque
data:
  connection-string: QWNjZXNzS2V5PXlvdXJhY2Nlc3NrZXk7QWNjb3VudE5hbWU9eW91cmFjY291bnRuYW1l  # Replace with your actual Azure connection string in base64
  sql-connection: U2VydmVyPXlvdXJzZXJ2ZXIuZGF0YWJhc2Uud2luZG93cy5uZXQ7RGF0YWJhc2U9YWktYXBwO1VzZXI9YWRtaW47UGFzc3dvcmQ9cGFzc3dvcmQ=  # Replace with your actual SQL connection string in base64
  speech-key: eW91cnNwZWVjaGtleQ==  # Replace with your actual Speech Service key in base64
  speech-region: d2VzdGV1cm9wZQ==  # Replace with your actual Speech Service region in base64
