apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla-mysql
spec:
  selector:
    matchLabels:
      app: joomla-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: joomla
        - name: MYSQL_USER
          value: joomla
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: joomla-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: joomla-mysql
