apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  replicas: 4
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
      - name: joomla
        image: joomla:latest
        ports:
        - containerPort: 80
        env:
        - name: JOOMLA_DB_HOST
          value: joomla-mysql
        - name: JOOMLA_DB_USER
          value: joomla
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: JOOMLA_DB_NAME
          value: joomla
---
apiVersion: v1
kind: Service
metadata:
  name: joomla
spec:
  selector:
    app: joomla
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
